spring:
    application:
        name: spring-boot-media-drive-service

    h2:
        console:
            enabled: true
            path: /h2

    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
        show-sql: true

    threads:
      virtual:
          enabled: true